version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udyam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../backend
    env_file:
      - ../backend/.env.example
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/udyam"
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
